### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by AmitMY** [bipinkrish/vscode-pose#1]
Amazing work.

If I may suggest something - 
the current solution embeds the bundle from unpkg. This is great for using the latest when internet connectivity is available, but when it is not, ideally I think there should be a local dist (even if it ends up a bit outdated, it is better than nothing)
https://github.com/bipinkrish/vscode-pose/blob/main/src/poseViewerProvider.ts#L51

**Comment by bipinkrish** [comment]
Good idea, i will try to implement it as soon as possible

**Comment by bipinkrish** [comment]
done, upgrade to `v0.0.3`
